/* events action */
export const EVENTS_LIST = 'EVENTS_LIST';
export const ADD_USER_EVENTS_LIST_INFO = 'ADD_USER_EVENTS_LIST_INFO';
export const ADD_RECOMMENDED_EVENTS = 'ADD_RECOMMENDED_EVENTS';
export const ADD_NEW_EVENTS = 'ADD_NEW_EVENTS';

/* authorize actions */
export const WRONG_CREDENTIALS = 'WRONG_CREDENTIALS';
export const CURRENT_CREDENTIALS = 'CURRENT_CREDENTIALS';
export const NO_USER_GET = 'NO_USER_GET';
export const SUCCESS_USER_GET = 'SUCCESS_USER_GET';

/* activity actions */
export const GET_ACTIVITIES_LIST_INFO = 'GET_ACTIVITIES_LIST_INFO';

export default {
  AUTHORIZATION: {
    LOGIN: '@AUTHORIZATION/LOGIN',
    LOGOUT: '@AUTHORIZATION/LOGOUT'
  },
  APPLICATION: {
    SHOW_ERROR_MESSAGE_GLOBAL: '@APPLICATION/SHOW_ERROR_MESSAGE_GLOBAL',
    SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL: '@APPLICATION/SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL',
    HIDE_MESSAGE_GLOBAL: '@APPLICATION/HIDE_MESSAGE_GLOBAL',
    SHOW_LOADING: '@APPLICATION/SHOW_LOADING',
    HIDE_LOADING: '@APPLICATION/HIDE_LOADING'
  },
  NOTIFICATIONS: {
    FETCH_LIST: '@NOTIFICATIONS/FETCH_LIST',
    FETCH_LIST_ERROR: '@NOTIFICATIONS/FETCH_LIST_ERROR',
    SET_LIST: '@NOTIFICATIONS/SET_LIST'
  },
  EVENTS: {
    JOIN_EVENT_REQUEST: '@EVENTS/JOIN_EVENT_REQUEST',
    JOIN_EVENT_SUCCESS: '@EVENTS/JOIN_EVENT_SUCCESS',
    JOIN_EVENT_ERROR: '@EVENTS/JOIN_EVENT_ERROR',
    REJECT_EVENT_REQUEST: '@EVENTS/REJECT_EVENT_REQUEST',
    REJECT_EVENT_SUCCESS: '@EVENTS/REJECT_EVENT_SUCCESS',
    REJECT_EVENT_ERROR: '@EVENTS/REJECT_EVENT_ERROR',
    EVENTS_LIST: '@EVENTS/EVENTS_LIST',
    ADD_USER_EVENTS_LIST_INFO: '@EVENTS/ADD_USER_EVENTS_LIST_INFO',
    ADD_RECOMMENDED_EVENTS: '@EVENTS/ADD_RECOMMENDED_EVENTS',
    ADD_NEW_EVENTS: '@EVENTS/ADD_NEW_EVENTS'
  },
  USERS: {
    FOLLOW_USER_REQUEST: '@USERS/FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS: '@USERS/FOLLOW_USER_SUCCESS',
    FOLLOW_USER_ERROR: '@USERS/FOLLOW_USER_ERROR'
  },
  USER: {
    SET_USER_PROFILE: '@USER_PROFILE/SET_USER_PROFILE'
  },
  COMMUNITIES: {
    JOIN_COMMUNITY_REQUEST: '@COMMUNITIES/JOIN_COMMUNITY_REQUEST',
    JOIN_COMMUNITY_SUCCESS: '@COMMUNITIES/JOIN_COMMUNITY_SUCCESS',
    JOIN_COMMUNITY_ERROR: '@COMMUNITIES/JOIN_COMMUNITY_ERROR',
    LEAVE_COMMUNITY_REQUEST: '@COMMUNITIES/LEAVE_COMMUNITY_REQUEST',
    LEAVE_COMMUNITY_SUCCESS: '@COMMUNITIES/LEAVE_COMMUNITY_SUCCESS',
    LEAVE_COMMUNITY_ERROR: '@COMMUNITIES/LEAVE_COMMUNITY_ERROR'
  }
};
