export default {
  AUTHORIZATION: {
    LOGIN_REQUEST: '@AUTHORIZATION/LOGIN_REQUEST',
    EXTERNAL_LOGIN_REQUEST: '@AUTHORIZATION/EXTERNAL_LOGIN_REQUEST',
    LOGIN_SUCCESS: '@AUTHORIZATION/LOGIN_SUCCESS',
    LOGIN_ERROR: '@AUTHORIZATION/LOGIN_ERROR',
    SIGN_UP_REQUEST: '@AUTHORIZATION/SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: '@AUTHORIZATION/SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: '@AUTHORIZATION/SIGN_UP_ERROR',
    LOGOUT: '@AUTHORIZATION/LOGOUT'
  },
  NOTIFICATIONS: {
    FETCH_LIST: '@NOTIFICATIONS/FETCH_LIST',
    FETCH_LIST_ERROR: '@NOTIFICATIONS/FETCH_LIST_ERROR',
    SET_LIST: '@NOTIFICATIONS/SET_LIST'
  },
  EVENTS: {
    JOIN_EVENT_REQUEST: '@EVENTS/JOIN_EVENT_REQUEST',
    JOIN_EVENT_SUCCESS: '@EVENTS/JOIN_EVENT_SUCCESS',
    JOIN_EVENT_ERROR: '@EVENTS/JOIN_EVENT_ERROR',
    REJECT_EVENT_REQUEST: '@EVENTS/REJECT_EVENT_REQUEST',
    REJECT_EVENT_SUCCESS: '@EVENTS/REJECT_EVENT_SUCCESS',
    REJECT_EVENT_ERROR: '@EVENTS/REJECT_EVENT_ERROR',
    EVENTS_LIST: '@EVENTS/EVENTS_LIST',
    ADD_USER_EVENTS_LIST_INFO: '@EVENTS/ADD_USER_EVENTS_LIST_INFO',
    ADD_RECOMMENDED_EVENTS: '@EVENTS/ADD_RECOMMENDED_EVENTS',
    ADD_NEW_EVENTS: '@EVENTS/ADD_NEW_EVENTS'
  },
  USERS: {
    FOLLOW_USER_REQUEST: '@USERS/FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS: '@USERS/FOLLOW_USER_SUCCESS',
    FOLLOW_USER_ERROR: '@USERS/FOLLOW_USER_ERROR'
  },
  USER: {
    SET_NOTIFICATIONS_INFO: '@USER_PROFILE/SET_NOTIFICATIONS_INFO',
    SET_USER_PROFILE: '@USER_PROFILE/SET_USER_PROFILE'
  },
  COMMUNITIES: {
    JOIN_COMMUNITY_REQUEST: '@COMMUNITIES/JOIN_COMMUNITY_REQUEST',
    JOIN_COMMUNITY_SUCCESS: '@COMMUNITIES/JOIN_COMMUNITY_SUCCESS',
    JOIN_COMMUNITY_ERROR: '@COMMUNITIES/JOIN_COMMUNITY_ERROR',
    LEAVE_COMMUNITY_REQUEST: '@COMMUNITIES/LEAVE_COMMUNITY_REQUEST',
    LEAVE_COMMUNITY_SUCCESS: '@COMMUNITIES/LEAVE_COMMUNITY_SUCCESS',
    LEAVE_COMMUNITY_ERROR: '@COMMUNITIES/LEAVE_COMMUNITY_ERROR'
  },
  LOGIN_PAGE: {
    CHANGE_FIELD: '@LOGIN_PAGE/CHANGE_FIELD',
    TOGGLE_LOADING: '@LOGIN_PAGE/TOGGLE_LOADING'
  },
  REGISTRATION_PAGE: {
    CHANGE_FIELD: '@REGISTRATION_PAGE/CHANGE_FIELD',
    TOGGLE_LOADING: '@REGISTRATION_PAGE/TOGGLE_LOADING'
  },
  REGISTRATION: {
    FETCH_ACTIVITIES_REQUEST: '@REGISTRATION/FETCH_ACTIVITIES_REQUEST',
    FETCH_ACTIVITIES_SUCCESS: '@REGISTRATION/FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_ERROR: '@REGISTRATION/FETCH_ACTIVITIES_ERROR',
    POST_PERSONAL_DATA_REQUEST: '@REGISTRATION/POST_PERSONAL_DATA_REQUEST',
    POST_PERSONAL_DATA_SUCCESS: '@REGISTRATION/POST_PERSONAL_DATA_SUCCESS',
    POST_PERSONAL_DATA_ERROR: '@REGISTRATION/POST_PERSONAL_DATA_ERROR',
    CREDENTIALS_INFO: '@REGISTRATION/CREDENTIALS_INFO',
    CHANGE_FIELD: '@REGISTRATION/CHANGE_FIELD',
    VALIDATE_FIELD: '@REGISTRATION/VALIDATE_FIELD',
    CHANGE_TAB_INDEX: '@REGISTRATION/CHANGE_TAB_INDEX',
    TOGGLE_ACTIVITY: '@REGISTRATION/TOGGLE_ACTIVITY'
  }
};
