/* users action */
export const ADD_USERS = 'ADD_USERS'
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const USER_INFO = 'USER_INFO'
export const CLEAR_ALL_DATA_USER = 'CLEAR_ALL_DATA_USER'
export const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE'
export const CLOSE_EDIT_PROFILE = 'CLOSE_EDIT_PROFILE'
export const ADD_PEOPLE_INFO = 'ADD_PEOPLE_INFO'

/* events action */
export const EVENT_INFO = 'EVENT_INFO'
export const EVENTS_LIST = 'EVENTS_LIST'
export const ADD_USER_EVENTS_LIST_INFO = 'ADD_USER_EVENTS_LIST_INFO'

/* notify actions */
export const ADD_NOTIFY = 'ADD_NOTIFY'
export const ADD_NOTIFY_LIST = 'ADD_NOTIFY_LIST'
export const DELETE_NOTIFY = 'DELETE_NOTIFY'
export const SEEN_NOTIFY = 'SEEN_NOTIFY'
export const CLEAR_ALL_DATA_NOTIFY = 'CLEAR_ALL_DATA_NOTIFY'

/* authorize actions */
export const GET_USER_ID = 'GET_USER_ID';
export const ADD_PROFILE = 'ADD_PROFILE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

/* global actions */
export const PROGRESS_CHANGE = 'PROGRESS_CHANGE'
export const DEFAULT_DATA_DISABLE = 'DEFAULT_DATA_DISABLE'
export const DEFAULT_DATA_ENABLE = 'DEFAULT_DATA_ENABLE'
export const LOADING = 'LOADING'
export const HIDE_MESSAGE_GLOBAL = 'HIDE_MESSAGE_GLOBAL'
export const SHOW_ERROR_MESSAGE_GLOBAL = 'SHOW_ERROR_MESSAGE_GLOBAL'
export const SHOW_NORMAL_MESSAGE_GLOBAL = 'SHOW_NORMAL_MESSAGE_GLOBAL'
export const SHOW_SEND_REQUEST_MESSAGE_GLOBAL = 'SHOW_SEND_REQUEST_MESSAGE_GLOBAL'
export const SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL = 'SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL'
export const SET_HEADER_TITLE = 'SET_HEADER_TITLE'
export const SHOW_TOP_LOADING = 'SHOW_TOP_LOADING'
export const HIDE_TOP_LOADING = 'HIDE_TOP_LOADING'
export const TEMP = 'TEMP'
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const CHANGE_DATA = 'CHANGE_DATA'
export const CHANGE_WINDOW_SIZE = 'CHANGE_WINDOW_SIZE'
export const SET_UID = 'SET_UID'

/* activity actions */
export const GET_ACTIVITIES_LIST_INFO = 'GET_ACTIVITIES_LIST_INFO';