/* events action */
export const EVENTS_LIST = 'EVENTS_LIST';
export const ADD_USER_EVENTS_LIST_INFO = 'ADD_USER_EVENTS_LIST_INFO';
export const ADD_RECOMMENDED_EVENTS = 'ADD_RECOMMENDED_EVENTS';
export const ADD_NEW_EVENTS = 'ADD_NEW_EVENTS';

/* authorize actions */
export const GET_USER_ID = 'GET_USER_ID';
export const ADD_PROFILE = 'ADD_PROFILE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const WRONG_CREDENTIALS = 'WRONG_CREDENTIALS';
export const CURRENT_CREDENTIALS = 'CURRENT_CREDENTIALS';
export const NO_USER_GET = 'NO_USER_GET';
export const SUCCESS_USER_GET = 'SUCCESS_USER_GET';

/* global actions */
export const HIDE_MESSAGE_GLOBAL = 'HIDE_MESSAGE_GLOBAL';
export const SHOW_ERROR_MESSAGE_GLOBAL = 'SHOW_ERROR_MESSAGE_GLOBAL';
export const SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL = 'SHOW_REQUEST_SUCCESS_MESSAGE_GLOBAL';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

/* activity actions */
export const GET_ACTIVITIES_LIST_INFO = 'GET_ACTIVITIES_LIST_INFO';

export default {
  NOTIFICATIONS: {
    FETCH_LIST: '@NOTIFICATIONS/FETCH_LIST',
    SET_LIST: '@NOTIFICATIONS/SET_LIST'
  },
  EVENTS: {
    JOIN_EVENT_REQUEST: '@EVENTS/JOIN_EVENT_REQUEST',
    JOIN_EVENT_SUCCESS: '@EVENTS/JOIN_EVENT_SUCCESS',
    JOIN_EVENT_ERROR: '@EVENTS/JOIN_EVENT_ERROR',
    REJECT_EVENT_REQUEST: '@EVENTS/REJECT_EVENT_REQUEST',
    REJECT_EVENT_SUCCESS: '@EVENTS/REJECT_EVENT_SUCCESS',
    REJECT_EVENT_ERROR: '@EVENTS/REJECT_EVENT_ERROR',
    EVENTS_LIST: '@EVENTS/EVENTS_LIST',
    ADD_USER_EVENTS_LIST_INFO: '@EVENTS/ADD_USER_EVENTS_LIST_INFO',
    ADD_RECOMMENDED_EVENTS: '@EVENTS/ADD_RECOMMENDED_EVENTS',
    ADD_NEW_EVENTS: '@EVENTS/ADD_NEW_EVENTS',
  }
}
